using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Shapes;
using VB6VisualMockupDesigner.Controls;
using VB6VisualMockupDesigner.Models;

namespace VB6VisualMockupDesigner.Helpers
{
    public static class Vb6Generator
    {
        private const double TwipsPerPixel = 15.0;

        /// <summary>
        /// Genera el código fuente completo de un archivo .frm de VB6 incluyendo Menús y Controles.
        /// </summary>
        public static string GenerateFrmCode(Canvas designSurface, string formTitle, List<MenuModel> menus)
        {
            string vbName = SanitizeVbName(formTitle);
            StringBuilder sb = new StringBuilder();

            // 1. CABECERA ESTÁNDAR
            sb.AppendLine("VERSION 5.00");
            sb.AppendLine($"' Generated by VB6 Visual Mockup Designer - {DateTime.Now}");
            sb.AppendLine($"Begin VB.Form {vbName} ");

            // 2. PROPIEDADES DEL FORMULARIO
            sb.AppendLine($"   Caption         =   \"{formTitle}\"");
            sb.AppendLine($"   ClientHeight    =   {Math.Round(designSurface.ActualHeight * TwipsPerPixel)}");
            sb.AppendLine($"   ClientWidth     =   {Math.Round(designSurface.ActualWidth * TwipsPerPixel)}");
            sb.AppendLine($"   ScaleHeight     =   {Math.Round(designSurface.ActualHeight * TwipsPerPixel)}");
            sb.AppendLine($"   ScaleWidth      =   {Math.Round(designSurface.ActualWidth * TwipsPerPixel)}");
            sb.AppendLine("   StartUpPosition =   3  'Windows Default");

            // 3. GENERACIÓN DE MENÚS (Bloque crítico para VB6)
            if (menus != null && menus.Count > 0)
            {
                WriteMenusToVb6(sb, menus);
            }

            // 4. GENERACIÓN DE CONTROLES (Recursivo)
            WriteChildrenRecursively(designSurface, sb, 3);

            sb.AppendLine("End");

            // 5. ATRIBUTOS OCULTOS DE VB6
            sb.AppendLine($"Attribute VB_Name = \"{vbName}\"");
            sb.AppendLine("Attribute VB_GlobalNameSpace = False");
            sb.AppendLine("Attribute VB_Creatable = False");
            sb.AppendLine("Attribute VB_PredeclaredId = True");
            sb.AppendLine("Attribute VB_Exposed = False");

            return sb.ToString();
        }

        private static void WriteMenusToVb6(StringBuilder sb, List<MenuModel> menus)
        {
            // VB6 anida los menús mediante bloques Begin...End. 
            // Como nuestra lista es plana con niveles, usamos recursividad o tracking de indentación.
            for (int i = 0; i < menus.Count; i++)
            {
                var m = menus[i];
                if (string.IsNullOrWhiteSpace(m.Name) && m.Caption != "-") continue;

                // En VB6 los menús suelen tener una indentación base de 3 espacios + nivel
                string indent = new string(' ', (m.Level + 1) * 3);
                string vbName = string.IsNullOrEmpty(m.Name) ? $"mnu{SanitizeVbName(m.Caption)}" : m.Name;

                sb.AppendLine($"{indent}Begin VB.Menu {vbName} ");
                sb.AppendLine($"{indent}   Caption         =   \"{m.Caption}\"");

                if (!m.Visible) sb.AppendLine($"{indent}   Visible         =   0  'False");
                if (!m.Enabled) sb.AppendLine($"{indent}   Enabled         =   0  'False");
                if (m.Checked) sb.AppendLine($"{indent}   Checked         =   -1 'True");

                if (!string.IsNullOrEmpty(m.Shortcut) && m.Shortcut != "(None)")
                {
                    sb.AppendLine($"{indent}   Shortcut        =   {m.Shortcut}");
                }

                // Si el SIGUIENTE item en la lista tiene un nivel mayor, este menú NO se cierra aún.
                // Si el siguiente tiene un nivel menor o igual, debemos cerrar este bloque y quizás padres.
                bool hasChildren = (i + 1 < menus.Count && menus[i + 1].Level > m.Level);

                if (!hasChildren)
                {
                    sb.AppendLine($"{indent}End");

                    // Si el siguiente elemento sube de nivel (ej: de 2 a 0), cerramos los niveles pendientes
                    if (i + 1 < menus.Count)
                    {
                        int nextLevel = menus[i + 1].Level;
                        int diff = m.Level - nextLevel;
                        for (int d = 0; d < diff; d++)
                        {
                            string parentIndent = new string(' ', (m.Level - d) * 3);
                            sb.AppendLine($"{parentIndent}End");
                        }
                    }
                    else
                    {
                        // Es el último item, cerrar todos los niveles hasta el 0
                        for (int d = m.Level; d > 0; d--)
                        {
                            string parentIndent = new string(' ', d * 3);
                            sb.AppendLine($"{parentIndent}End");
                        }
                    }
                }
            }
        }

        private static void WriteChildrenRecursively(Panel container, StringBuilder sb, int indentLevel)
        {
            string indent = new string(' ', indentLevel);

            foreach (UIElement child in container.Children)
            {
                if (child is FrameworkElement fe)
                {
                    // Filtros Anti-Basura visual del diseñador
                    if (fe.Name == "SelectionRect" || fe.Name == "QuickEditBox" ||
                        fe.Name == "SnapLineOverlay" || fe.Name == "InfoTip" ||
                        fe.Tag is ResizeDirection) continue;

                    if (fe is Border && fe.Tag == null && !fe.IsHitTestVisible) continue;
                    if ((fe is Rectangle || fe is Ellipse || fe is Path) && fe.Tag == null) continue;

                    if (fe.GetType().Name.Contains("Adorner")) continue;
                    string vbType = GetVbType(fe);
                    if (vbType == "VB.Unknown") continue;

                    string name = string.IsNullOrEmpty(fe.Name) ? "Control" : fe.Name;

                    sb.AppendLine($"{indent}Begin {vbType} {name} ");

                    double left = Canvas.GetLeft(fe);
                    double top = Canvas.GetTop(fe);
                    if (double.IsNaN(left)) left = 0;
                    if (double.IsNaN(top)) top = 0;

                    sb.AppendLine($"{indent}   Left            =   {Math.Round(left * TwipsPerPixel)}");
                    sb.AppendLine($"{indent}   Top             =   {Math.Round(top * TwipsPerPixel)}");
                    sb.AppendLine($"{indent}   Width           =   {Math.Round(fe.ActualWidth * TwipsPerPixel)}");
                    sb.AppendLine($"{indent}   Height          =   {Math.Round(fe.ActualHeight * TwipsPerPixel)}");

                    if (fe is Control c)
                    {
                        WriteFontBlock(sb, c, indent + "   ");
                        if (c.Background is SolidColorBrush bg)
                            sb.AppendLine($"{indent}   BackColor       =   {ColorToVbHex(bg.Color)}");
                        if (c.Foreground is SolidColorBrush fg)
                            sb.AppendLine($"{indent}   ForeColor       =   {ColorToVbHex(fg.Color)}");
                    }
                    else if (fe is Border b) // Para PictureBox o Frames simulados con Border
                    {
                        if (b.Background is SolidColorBrush bg)
                            sb.AppendLine($"{indent}   BackColor       =   {ColorToVbHex(bg.Color)}");
                    }

                    if (fe is ContentControl cc && cc.Content is string cap)
                        sb.AppendLine($"{indent}   Caption         =   \"{cap}\"");
                    else if (fe is TextBox tb)
                        sb.AppendLine($"{indent}   Text            =   \"{tb.Text}\"");
                    else if (fe is TextBlock txt)
                        sb.AppendLine($"{indent}   Caption         =   \"{txt.Text}\"");

                    int? idx = VB6Data.GetIndex(fe);
                    if (idx.HasValue) sb.AppendLine($"{indent}   Index           =   {idx.Value}");

                    Canvas innerCanvas = GetChildCanvas(fe);
                    if (innerCanvas != null && innerCanvas.Children.Count > 0)
                    {
                        WriteChildrenRecursively(innerCanvas, sb, indentLevel + 3);
                    }

                    sb.AppendLine($"{indent}End");
                }
            }
        }

        private static void WriteFontBlock(StringBuilder sb, Control ctrl, string localIndent)
        {
            var ff = ctrl.FontFamily;
            var fs = ctrl.FontSize;
            var fw = ctrl.FontWeight;
            var fstyle = ctrl.FontStyle;

            sb.AppendLine($"{localIndent}BeginProperty Font ");
            sb.AppendLine($"{localIndent}   Name            =   \"{ff.Source}\"");
            sb.AppendLine($"{localIndent}   Size            =   {Math.Round(fs * 0.75, 2)}");
            sb.AppendLine($"{localIndent}   Charset         =   0");
            sb.AppendLine($"{localIndent}   Weight          =   {(fw == FontWeights.Bold ? 700 : 400)}");
            sb.AppendLine($"{localIndent}   Underline       =   0   'False");
            sb.AppendLine($"{localIndent}   Italic          =   {(fstyle == FontStyles.Italic ? -1 : 0)}");
            sb.AppendLine($"{localIndent}   Strikethrough   =   0   'False");
            sb.AppendLine($"{localIndent}EndProperty");
        }

        private static string GetVbType(FrameworkElement element)
        {
            if (element.Tag is string tagType && !string.IsNullOrEmpty(tagType))
            {
                switch (tagType)
                {
                    case "CommandButton": return "VB.CommandButton";
                    case "Label": return "VB.Label";
                    case "TextBox": return "VB.TextBox";
                    case "CheckBox": return "VB.CheckBox";
                    case "OptionButton": return "VB.OptionButton";
                    case "Frame": return "VB.Frame";
                    case "PictureBox": return "VB.PictureBox";
                    case "ComboBox": return "VB.ComboBox";
                    case "ListBox": return "VB.ListBox";
                    case "Timer": return "VB.Timer";
                    case "Image": return "VB.Image";
                    case "Shape": return "VB.Shape";
                    case "Line": return "VB.Line";
                    case "SSPanel": return "Threed.SSPanel";
                    case "SSCommand": return "Threed.SSCommand";
                    case "SSCheck": return "Threed.SSCheck";
                    case "SSOption": return "Threed.SSOption";
                    case "SSFrame": return "Threed.SSFrame";
                }
            }
            if (element is Button) return "VB.CommandButton";
            if (element is Label) return "VB.Label";
            if (element is TextBox) return "VB.TextBox";
            return "VB.Unknown";
        }

        private static string ColorToVbHex(Color c) => $"&H00{c.B:X2}{c.G:X2}{c.R:X2}&";

        private static string SanitizeVbName(string input)
        {
            if (string.IsNullOrEmpty(input)) return "Form1";
            string clean = new string(input.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray());
            return string.IsNullOrEmpty(clean) ? "Form1" : clean;
        }

        private static Canvas GetChildCanvas(FrameworkElement container)
        {
            if (container is GroupBox gb) return gb.Content as Canvas;
            if (container is Border b && b.Child is Canvas c) return c;
            if (container is Border bp && bp.Child is Grid g)
                return g.Children.OfType<Canvas>().FirstOrDefault();
            return null;
        }
    }
}